# Project information
site_name: 'CrossGenerate v2.1.0'

# Copyright
copyright: 'Copyright &copy; 2018 - CrossBreeze'

# Configuration
theme:
  name: 'material'
  logo: 'img/xgen-icon.png'
  favicon: 'img/favicon.ico'
  language: 'en'
  palette:
    primary: 'blue grey'
    accent: 'green'
  feature:
    tabs: true

# Pages
pages:
- Home:
    - 'Introduction'    : 'index.md'
    - 'Getting started' : 'GettingStarted.md'
    - 'Overview'        : 'Overview.md'
- Model:
    - 'Introduction'    : 'Model/index.md'
- Template:
    - 'Introduction'    : 'Template/index.md'
    - 'Text template'   : 'Template/TextTemplate/index.md'
    - 'XML template'    : 'Template/XmlTemplate/index.md'
    - 'Annotation':
        - 'Overview'                : 'Template/Annotation/index.md'
        - 'TextSection'             : 'Template/Annotation/TextSection.md'
        - 'XmlSection'              : 'Template/Annotation/XmlSection.md'
        - 'Comment'                 : 'Template/Annotation/Comment.md'
- Binding:
    - 'Introduction'    : 'Binding/index.md'
- Config:
    - 'Configuration'   : 'Config/index.md'
    - 'Model'           : 'Config/Model.md'
    - 'Template':
        - 'XmlTemplate'           : 'Config/Template/XmlTemplate.md'
        - 'TextTemplate'          : 'Config/Template/TextTemplate.md'
        - 'Generic options'   : 'Config/Template/GenericTemplate.md'
    - 'Binding'         : 'Config/Binding.md'
- Examples:
    - 'Overview'        : 'Examples/index.md'
    - 'Model':
        - 'Source model'     : 'Examples/Model/Source_model.md'
#        - 'DWH model'        : 'Examples/Model/DWH_model.md'
    - 'SQL':
        - 'Simple staging'   : 'Examples/SQL/Simple_staging.md'
    - 'Microsoft SSIS':
        - 'Simple staging'   : 'Examples/Microsoft_SSIS/Simple_staging.md'
    - 'Informatica PowerCenter':
        - 'Simple staging'   : 'Examples/Informatica_PowerCenter/Simple_staging.md'
    - 'IBM DataStage':
        - 'Simple staging'   : 'Examples/IBM_DataStage/Simple_staging.md'

# Extra
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/CrossBreeze_NL'

# Extensions
markdown_extensions:
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde