on:
  workflow_call:
  
env:
  JAVA_VERSION: 11
  MAVEN_VERSION: 3.8.6

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      # Checkout the code.
      - name: checkout
        uses: actions/checkout@v4
  
      # Setup Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '${{ env.JAVA_VERSION }}'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode verify
        working-directory: ./XGenerate