on:
  workflow_call:
  
env:
  JAVA_VERSION: 11
  MAVEN_VERSION: 3.8.6

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      # Checkout the code
      - name: checkout
        uses: actions/checkout@v4
  
      # Setup Java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '${{ env.JAVA_VERSION }}'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
      
      # Build with Maven
      - name: Build
        run: mvn --batch-mode install -DskipTests
        working-directory: ./XGenerate

      # Test with Maven
      - name: Run Unit Tests
        run: mvn --batch-mode test -Dtest="RunXGenerateLibUnitTest"
        working-directory: ./XGenerate

      # Build single jar
      - name: Assemble Jar
        run: mvn --batch-mode assembly:single -DskipTests
        working-directory: ./XGenerate