on:
  workflow_call:
  
env:
  JAVA_VERSION: 11
  MAVEN_VERSION: 3.8.6

defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      # Checkout the code
      - name: checkout
        uses: actions/checkout@v4
  
      # Setup Java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '${{ env.JAVA_VERSION }}'
          distribution: 'temurin'
          architecture: x64
          cache: 'maven'
      
      # Build with Maven
      - name: Build
        run: mvn --batch-mode install -DskipTests
        working-directory: ./XGenerate

      # Test with Maven
      - name: Run Unit Tests
        run: mvn --batch-mode test -Dtest="RunXGenerateLibUnitTest"
        working-directory: ./XGenerate

      - name: Test Report
        uses: phoenix-actions/test-reporting@v12
        id: test-report               # Set ID reference for step
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: test-results
          path: XGenerate/target/surefire-reports/TEST-*.xml
          reporter: java-junit

      # Build single jar
      - name: Assemble Jar
        run: mvn --batch-mode assembly:single -DskipTests
        working-directory: ./XGenerate

      # Publish jars.
      - uses: actions/upload-artifact@v4
        with:
          name: jar-without-dependencies
          path: XGenerate/target/XGenerate-([0-9.])+.jar
          compression-level: 0 # no compression, since jar is already compressed
      - uses: actions/upload-artifact@v4
        with:
          name: jar-with-dependencies
          path: XGenerate/target/XGenerate-([0-9.])+-with-dependencies.jar
          compression-level: 0 # no compression, since jar is already compressed